"""Retained prototype checks; --output must name a new evidence directory."""
import json
from pathlib import Path
from playwright.sync_api import sync_playwright
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from browser_checks import prepare_check
root = Path(__file__).parent
preview_url, artifacts = prepare_check(root/'spec-studio.html')
checks=[]
with sync_playwright() as p:
    browser=p.chromium.launch()
    page=browser.new_page(viewport={'width':1080,'height':1000})
    page.set_default_timeout(6000)
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(preview_url)
    f=page.frame_locator('iframe')
    def click(name): f.get_by_role('button',name=name,exact=True).click()
    click('Shape this idea →')
    f.get_by_label('Goal',exact=True).fill('')
    click('Continue to research →')
    assert 'Add a goal' in f.get_by_role('alert').inner_text()
    f.get_by_label('Goal',exact=True).fill('Help developers resume saved work with clear decisions.')
    click('Continue to research →')
    click('Mine sample context')
    f.get_by_label('Use in this spec: Keep the task primary and offer host-specific entry points.').check()
    assert 'Fictional conflict example' in f.locator('main').inner_text()
    click('Load sample research')
    f.get_by_label('Carry this implication and its source into the spec').first.check()
    click('Continue with selected findings →')
    assert f.get_by_role('button',name='Compare approaches →',exact=True).is_disabled()
    f.get_by_role('button',name='Shared local task record',exact=False).click()
    f.get_by_role('button',name='Start execution immediately',exact=False).click()
    assert f.get_by_role('button',name='Compare approaches →',exact=True).is_disabled()
    f.get_by_role('button',name='Show a resume preview',exact=False).click()
    click('Save & close')
    click('Continue saved draft →')
    assert f.get_by_role('button',name='Show a resume preview',exact=False).get_attribute('aria-pressed')=='true'
    checks.append('Empty intent and unresolved/unsupported decisions block progression; save/reopen preserves answers')
    click('Compare approaches →')
    click('Choose host panels')
    click('Choose shared companion')
    click('Create sample specification →')
    assert 'One task, several surfaces' not in f.locator('main').inner_text()
    assert 'Use a shared task record' in f.locator('main').inner_text()
    checks.append('Research implication and chosen approach are incorporated into the spec')
    f.get_by_role('button',name='Review this revision →',exact=True).first.click()
    assert f.get_by_role('button',name='Inspect acceptance & handoff →',exact=True).is_disabled()
    click('Apply suggested requirement')
    click('Run sample review for r2')
    click('Inspect acceptance & handoff →')
    click('Accept revision 2 in this demo')
    assert 'Not granted' in f.locator('main').inner_text()
    click('Prepare a memory candidate')
    assert 'Nothing was written to project memory' in f.locator('main').inner_text()
    click('Prepare handoff text')
    assert 'Keep the task primary' in f.get_by_label('Handoff text').inner_text()
    assert 'Revision: 2' in f.get_by_label('Handoff text').inner_text()
    assert 'https://opencode.ai/docs/web/' in f.get_by_label('Handoff text').inner_text()
    click('Back to workflow')
    checks.append('Review finding creates revision 2; fresh review enables exact-revision acceptance; export carries sources and no execution grant')
    click('Edit accepted spec')
    f.get_by_label('Included scope',exact=True).fill('Local task list, decision-first sorting, resume preview, and project labels.')
    f.get_by_label('Goal',exact=True).click()
    assert 'Draft r3' in f.locator('main').inner_text()
    f.locator('aside button[data-action="go:6"]').click()
    assert f.get_by_role('button',name='Accept revision 3 in this demo',exact=True).is_disabled()
    f.locator('aside button[data-action="go:history"]').click()
    assert 'Simulated acceptance' in f.locator('main').inner_text()
    checks.append('Editing accepted spec revokes acceptance, requires fresh review and retains earlier acceptance history')
    for width in [320,736,1024]:
        page.set_viewport_size({'width':width,'height':1000})
        for n in range(7):
            f.locator(f'aside button[data-action="go:{n}"]').click()
            dims=page.frames[1].evaluate('({scroll:document.documentElement.scrollWidth,width:innerWidth})')
            assert dims['scroll']<=dims['width'],(width,n,dims)
        checks.append(f'All seven workflow screens fit {width}px viewport')
    f.locator('aside button[data-action="go:5"]').click()
    click('Run sample review for r3')
    click('Inspect acceptance & handoff →')
    f.get_by_label('Entry point').select_option('Antigravity')
    click('Accept revision 3 in this demo')
    assert 'Build handoff · Antigravity' in f.locator('main').inner_text()
    checks.append('Re-review accepts revision 3; Antigravity selection carries into handoff')
    checks.append('Context provenance, conflicting-memory exclusion, and a non-writing memory candidate are visible')
    # The fixture host provides widgetState persistence for this browser session. Verify the visible state survives reload.
    page.reload()
    assert 'Accepted. Ready to prepare the build.' in f.locator('main').inner_text()
    checks.append('Reload restores accepted revision and selected host through the local fixture host')
    page.set_viewport_size({'width':1080,'height':1000})
    page.screenshot(path=str(artifacts/'acceptance-light.png'),full_page=True)
    page.emulate_media(color_scheme='dark')
    f.locator('aside button[data-action="go:1"]').click()
    page.screenshot(path=str(artifacts/'research-dark.png'),full_page=True)
    assert not errors,errors
    checks.append('No JavaScript errors during exercised journeys')
    browser.close()
(artifacts/'verification.json').write_text(json.dumps({'result':'passed','checks':checks,'limitations':['Deterministic sample spec, research and review','No live AI host or Harness authority integration','No implementation checks run','No human usability walkthrough']},indent=2)+'\n')
print(json.dumps(checks,indent=2))
